In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train_df=pd.read_csv("fashion-mnist_train.csv")
test_df=pd.read_csv("fashion-mnist_test.csv")
train_df.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to pixel784
dtypes: int64(785)
memory usage: 359.3 MB

In [4]:
train_df.describe()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
count,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,...,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.00000
mean,4.500000,0.000900,0.006150,0.035333,0.101933,0.247967,0.411467,0.805767,2.198283,5.682000,...,34.625400,23.300683,16.588267,17.869433,22.814817,17.911483,8.520633,2.753300,0.855517,0.07025
std,2.872305,0.094689,0.271011,1.222324,2.452871,4.306912,5.836188,8.215169,14.093378,23.819481,...,57.545242,48.854427,41.979611,43.966032,51.830477,45.149388,29.614859,17.397652,9.356960,2.12587
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,4.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,58.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,9.000000,16.000000,36.000000,226.000000,164.000000,227.000000,230.000000,224.000000,255.000000,254.000000,...,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,170.00000

In [5]:
x_train=train_df.iloc[:,1:].to_numpy()
x_train=x_train.reshape(-1,28,28,1)
x_train=x_train/255
y_train=train_df.iloc[:,1].to_numpy()
y_train=y_train/255

In [6]:
x_test=test_df.iloc[:,1:].to_numpy()
x_test=x_test.reshape(-1,28,28,1)
x_test=x_test/255
y_test=test_df.iloc[:,1].to_numpy()
y_test=y_test/255

In [7]:
from tensorflow import keras
num_classes=10
y_train=keras.utils.to_categorical(y_train,num_classes)
y_test=keras.utils.to_categorical(y_test,num_classes)

In [8]:
import tensorflow as tf
from tensorflow.keras import layers

In [13]:
model=keras.Sequential([
    layers.Reshape(target_shape=(28,28,1), input_shape=(28,28)),
    layers.Conv2D(filters=16,kernel_size=(3,3),activation='relu'),
    layers.MaxPooling2D(pool_size=(2,2)),
    layers.Flatten(),
    layers.Dense(units=64,activation='relu'),
    layers.Dense(units=10,activation='softmax')
])
model.compile(optimizer='adam',loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 reshape_1 (Reshape)         (None, 28, 28, 1)         0

 conv2d_1 (Conv2D)           (None, 26, 26, 16)        160

 max_pooling2d_1 (MaxPooling  (None, 13, 13, 16)       0
 2D)

 flatten_1 (Flatten)         (None, 2704)              0

 dense_2 (Dense)             (None, 64)                173120

 dense_3 (Dense)             (None, 10)                650

=================================================================
Total params: 173,930
Trainable params: 173,930
Non-trainable params: 0
_________________________________________________________________

In [14]:
y_train.shape

(60000, 10)

In [15]:
history = model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.1)

Epoch 1/10
1688/1688 [==============================] - 20s 11ms/step - loss: 0.0039 - accuracy: 0.9994 - val_loss: 5.9285e-07 - val_accuracy: 1.0000
Epoch 2/10
1688/1688 [==============================] - 19s 11ms/step - loss: 2.2816e-07 - accuracy: 1.0000 - val_loss: 5.0346e-08 - val_accuracy: 1.0000
Epoch 3/10
1688/1688 [==============================] - 20s 12ms/step - loss: 3.6502e-08 - accuracy: 1.0000 - val_loss: 1.2537e-08 - val_accuracy: 1.0000
Epoch 4/10
1688/1688 [==============================] - 19s 11ms/step - loss: 1.1883e-08 - accuracy: 1.0000 - val_loss: 4.1127e-09 - val_accuracy: 1.0000
Epoch 5/10
1688/1688 [==============================] - 19s 11ms/step - loss: 4.7772e-09 - accuracy: 1.0000 - val_loss: 1.5895e-09 - val_accuracy: 1.0000
Epoch 6/10
1688/1688 [==============================] - 18s 11ms/step - loss: 2.2208e-09 - accuracy: 1.0000 - val_loss: 6.3578e-10 - val_accuracy: 1.0000
Epoch 7/10
1688/1688 [==============================] - 19s 11ms/step - loss: 1.0883e-09 - accuracy: 1.0000 - val_loss: 2.5829e-10 - val_accuracy: 1.0000
Epoch 8/10
1688/1688 [==============================] - 18s 11ms/step - loss: 5.6072e-10 - accuracy: 1.0000 - val_loss: 1.1921e-10 - val_accuracy: 1.0000
Epoch 9/10
1688/1688 [==============================] - 18s 11ms/step - loss: 2.6712e-10 - accuracy: 1.0000 - val_loss: 1.9868e-11 - val_accuracy: 1.0000
Epoch 10/10
1688/1688 [==============================] - 18s 11ms/step - loss: 1.4129e-10 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000

In [16]:
test_loss,acc=model.evaluate(x_test,y_test)
test_loss

313/313 [==============================] - 2s 5ms/step - loss: 1.7881e-10 - accuracy: 1.0000

1.7881388036933288e-10

In [17]:
acc

1.0